config/routes.rb
Rails.application.routes.draw do
	resources :airports

  get 'bookings/new'

	resources :flights

	get 'flight_list',  :to => 'flights#all' 
	root 'flights#index'

	get 'bookings_list', :to => 'bookings#all'

	resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, :foreign_key => "from_airport_id", :class_name => "Flight"
	has_many :arriving_flights, :foreign_key => "to_airport_id", :class_name => "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  
  has_many :passengers, through: :passenger_bookings
  has_many :passenger_bookings

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, :class_name => "Airport"
	belongs_to :to_airport, :class_name => "Airport"

	has_many :passengers, through: :bookings	
	has_many :bookings

	def self.find_flight(from, to, date)
		x = date.to_time
		Flight.where(from_airport_id: from, to_airport_id: to, start: (x)..(x + 1.day))
	end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	
  has_many :bookings, through: :passenger_bookings
  has_many :passenger_bookings

  has_many :flights, through: :bookings
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
	def index
  	@airports = Airport.all
  end

  def show
  	@airport = Airport.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    #passenger count
    @passenger_count = params[:passengers]

    #flight id
  	@flight_id = params[:flight_id]

    #display info
  	@flight = Flight.find(@flight_id)
  	@from_airport = Airport.find(@flight.from_airport)
  	@to_airport = Airport.find(@flight.to_airport)

    @booking = Booking.new(flight_id: params[:flight_id])

    @passenger_count.to_i.times do
      @booking.passengers.build
    end

  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        @user = passenger
        PassengerMailer.thank_you(@user).deliver_now
      end
      redirect_to @booking
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  def all
    @bookings = Booking.all
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@airports = Airport.all.map {|u| [u.shortened_name, u.id]}
		@passenger_count = [1,2,3,4]
		@dates = Flight.all.map {|u| [u.start.to_date]}.uniq
	end

	def all
		@flights = Flight.all
	end

	def show
		@flight = Flight.find(params[:id])
	end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_controller_helper.rb
module FlightsControllerHelper
end

app/views/airports/index.html.erb
<% @airports.each do |airportr| %>
<%= link_to airportr.full_name, airportr %><br>
<% end %>

app/views/airports/show.html.erb
<h1><%= @airport.full_name %></h1>
<% @airport.departing_flights.each do |flight| %>
	<% @flight = flight %>
  <%= link_to "Show Flight", flight %><br>
	<%= render 'shared/flight_info' %>
<% end %>

app/views/bookings/_passenger_form.html.erb
Passenger: <%= @num + 1 %>

<br>

app/views/bookings/all.html.erb
Bookings: <br><br>
<% @bookings.each do |x| %>
<%= link_to x.id, x %><br>
<% end %>

app/views/bookings/new.html.erb
<%= render 'shared/flight_info' %>

<%= form_for(@booking) do |f| %>
	<%= f.hidden_field(:flight_id) %>

	<%= f.fields_for :passengers do |pass| %>
		Name: <%= pass.text_field :name %><br>
		Email: <%= pass.text_field :email %><br><br>
	<% end %>

<%= f.submit %>

<% end %>

app/views/bookings/show.html.erb
<%= render 'shared/flight_info' %>

Passengers: <br><br>
<% @booking.passengers.each do |x| %>
- <%= x.name %><br>
<% end %>

app/views/flights/_results.html.erb
Flights available:<br>

<%= form_tag("bookings/new", method: "get") do %>
	<% @results.each do |x| %>
		<%= radio_button_tag :flight_id, x.id %>
		<%= x.start %> <br>
	<% end %>
	<%= hidden_field_tag(:passengers, params[:people]) %>
	<%= submit_tag("Next step") %>
<% end %>

app/views/flights/all.html.erb
<% @flights.each do |flight| %>
	<% @flight = flight %>
	<%= link_to "Show Flight", flight%><br>
	<%= render 'shared/flight_info' %>
<% end %>

app/views/flights/index.html.erb
<%= form_tag("flights#index", method: "get") do %>
	<%= label_tag 'From: ' %>
	<%= select_tag(:from_airport, options_for_select(@airports)) %><br><br>
	<%= label_tag 'To:' %>
	<%= select_tag(:to_airport, options_for_select(@airports)) %><br><br>

	<%= label_tag 'Passengers' %>
	<%= select_tag :people, options_for_select(@passenger_count) %><br><br>

	<%= label_tag 'Date' %>
	<%= select_tag("dates", options_for_select(@dates)) %><br><br>

	<%= submit_tag("Search") %>
<% end %>
<br>

<% if params.has_key?(:to_airport) %>
		<% @to_airport = Airport.find(params[:to_airport]) %>
		<% @from_airport = Airport.find(params[:from_airport]) %>
		<% @people = params[:people] %>
		<% @date = params[:dates] %>
		<% @results = Flight.find_flight(@from_airport, @to_airport, @date) %>
<%= render 'results' %>
<% end %>

app/views/flights/show.html.erb
<%= render 'shared/flight_info' %>

Passengers:<br>
<% @flight.passengers.each do |x| %>
- <%= x.name %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path %> | 
  <%= link_to "Flights", flight_list_path %> | 
  <%= link_to "Bookings", bookings_list_path %> | 
  <%= link_to "Airports", airports_path %>
  <br><br>----------------------------------------------<br><br>
    <%= yield %>
  </body>
</html>

app/views/shared/_flight_info.html.erb
<% @from_airport = Airport.find(@flight.from_airport_id) %>
<%= @from_airport.full_name %> ->
<% @to_airport = Airport.find(@flight.to_airport_id) %>
<%= @to_airport.full_name %><br>
Departure: <%= @flight.start %><br>
ID: <%= @flight.id %>
<br><br>